version: '2.0'
services:
  db:
    image: postgres:9.6
  web:
    build: .
    environment:
      - PORT=5000
    env_file: .env
    command: rails server
    volumes:
      - .:/familiar
    ports:
      - "5000:5000"
    links:
      - db
  worker:
    build: .
    env_file: .env
    command: rake jobs:work
    volumes:
      - .:/familiar
    tmpfs:
      - /tmp
    links:
      - db